Repository poloz-lab/PADIVAR-Hardware, pull requests merged in 2021-03, with the labels that each got.

#72 Close #6 elm327 initialization
  src/device.cpp
  src/device.h
  src/elm327.cpp
Labels: enhancement

#73 close #18 pid class
  src/pid.cpp
  src/pid.h
Labels: enhancement

#71 Use StateInterpreterTypes in main instead of integer
  src/main.cpp
Labels: enhancement

#67 connection with wifi
  src/wifi.cpp
  src/wifi.h
Labels: enhancement

#78 create verbose to monitor bluetooth activity
  src/bluetooth.cpp
  src/server_socket.cpp
Labels: enhancement

#75 Close #16 elm327 send obd
  src/elm327.cpp
  src/elm327.h
Labels: enhancement

#82 Close #17 send pid function
  src/device.cpp
  src/device.h
  src/pid.cpp
  src/pid.h
Labels: enhancement

#91 Close #90 waiting for connection returns pointer
  src/main.cpp
  src/server_socket.cpp
  src/server_socket.h
Labels: enhancement

#92 Close #89 destructor for session
  src/session.cpp
Labels: bug

#93 Close #88 device destructor
  src/device.cpp
  src/device.h
Labels: bug

#96 Close #94 destructor for interface
  src/interface.cpp
  src/interface.h
Labels: bug

#85 Close #84 command for client send pid
  src/session.cpp
  src/session.h
Labels: enhancement

#108 Close #107 add return in sendPID
  src/session.cpp
Labels: bug

#109 Close #97 bluetooth documentation
  src/bluetooth.cpp
  src/bluetooth.h
Labels: documentation

#111 Close #99 elm327 documentation
  src/elm327.cpp
  src/elm327.h
Labels: documentation

#106 add the command repeatPID in the interpreter
  src/session.cpp
Labels: enhancement

#113 Close #104 wifi documentation
  src/wifi.cpp
  src/wifi.h
Labels: documentation

#114 close #7 available pid detection
  src/device.cpp
  src/device.h
Labels: enhancement

#110 readme creation
  README.md
Labels: documentation

#116 Close #101 pid documentation
  src/pid.cpp
  src/pid.h
Labels: documentation

#118 Close #103 session documentation
  src/session.cpp
  src/session.h
Labels: documentation

#120 Close #100 Interface documentation
  src/interface.cpp
  src/interface.h
Labels: documentation

#122 Close #98 device documentation
  src/device.cpp
  src/device.h
Labels: documentation

#130 Close #125 compatibility with telnet
  src/server_socket.cpp
Labels: enhancement
