Repository poloz-lab/PADIVAR-Hardware, pull requests merged in 2021-02, with the labels that each got.

#49 Fix #48 bug only a part of the string is sent through the socket
  src/server_socket.cpp
Labels: bug

#50 Close #44 send list available pid by software
  src/pid.cpp
  src/pid.h
  src/session.cpp
  src/session.h
Labels: enhancement

#51 Close #45 missing ! in enum ExceptionSessionType doc
  src/session.h
Labels: documentation

#52 Close #43 sending error through client socket when exception is thrown
  src/main.cpp
Labels: enhancement

#53 Close #31 missing documentation session
  src/session.h
Labels: documentation

#55 Close #47 initialize Session with no device
  src/session.cpp
Labels: enhancement

#59 Close #5 bluetooth connection
  Makefile
  dependencies.txt
  src/bluetooth.cpp
  src/bluetooth.h
Labels: enhancement

#61 Close #60 verbose mode
  src/main.cpp
  src/server_socket.cpp
  src/session.cpp
Labels: enhancement

#62 Close #22 send receive bluetooth
  src/bluetooth.cpp
  src/bluetooth.h
  src/interface.h
  src/usb.cpp
  src/usb.h
  src/wifi.cpp
  src/wifi.h
Labels: enhancement

#63 Close #54 delete session with exception
  src/main.cpp
Labels: bug
